import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Получаем __dirname в ES модулях
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function imageToBase64(imagePath) {
  try {
    const fileContent = fs.readFileSync(imagePath);
    const base64 = fileContent.toString('base64');
    const ext = path.extname(imagePath).slice(1).toLowerCase();
    const mimeType = getMimeType(ext);
    return `data:${mimeType};base64,${base64}`;
  } catch (error) {
    console.error(`Ошибка чтения ${imagePath}:`, error.message);
    return null;
  }
}

function getMimeType(ext) {
  const types = {
    'png': 'image/png',
    'jpg': 'image/jpeg',
    'jpeg': 'image/jpeg',
    'gif': 'image/gif',
    'webp': 'image/webp',
    'svg': 'image/svg+xml',
    'woff': 'font/woff',
    'woff2': 'font/woff2',
    'ttf': 'font/ttf',
    'otf': 'font/otf',
    'mp3': 'audio/mpeg',
    'wav': 'audio/wav',
    'ogg': 'audio/ogg'
  };
  return types[ext] || 'application/octet-stream';
}

function processAssets(dir, baseDir = '') {
  const result = {};
  
  try {
    const items = fs.readdirSync(dir);
    
    for (const item of items) {
      const fullPath = path.join(dir, item);
      const relativePath = baseDir ? path.join(baseDir, item) : item;
      const stat = fs.statSync(fullPath);
      
      if (stat.isDirectory()) {
        // Это папка - рекурсивно обрабатываем
        const subResult = processAssets(fullPath, relativePath);
        if (Object.keys(subResult).length > 0) {
          result[item] = subResult;
        }
      } else {
        // Это файл - конвертируем если это изображение
        const ext = path.extname(item).toLowerCase().slice(1);
        if (['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg'].includes(ext)) {
          const base64 = imageToBase64(fullPath);
          if (base64) {
            const key = path.basename(item, path.extname(item));
            result[key] = base64;
            console.log(`✓ ${relativePath}`);
          }
        }
      }
    }
  } catch (error) {
    console.error(`Ошибка обработки ${dir}:`, error.message);
  }
  
  return result;
}

function main() {
  console.log('🚀 Генерация IMAGE_DATA для проекта...\n');
  
  // Пути для поиска изображений
  const possiblePaths = [
    path.join(__dirname, 'assets'),
    path.join(__dirname, 'public', 'assets'),
    path.join(__dirname, 'src', 'assets')
  ];
  
  let assetsDir = null;
  for (const possiblePath of possiblePaths) {
    if (fs.existsSync(possiblePath)) {
      assetsDir = possiblePath;
      console.log(`Найдена папка с ассетами: ${assetsDir}`);
      break;
    }
  }
  
  if (!assetsDir) {
    console.error('❌ Папка с изображениями не найдена!');
    console.log('Создайте папку assets/ в корне проекта с изображениями');
    return;
  }
  
  const outputFile = path.join(__dirname, 'js', 'imageData.js');
  
  // Сканируем и конвертируем изображения
  const imageData = processAssets(assetsDir);
  
  if (Object.keys(imageData).length === 0) {
    console.error('❌ Не найдено изображений для конвертации!');
    return;
  }
  
  // Создаем JS файл с экспортом
  const content = `// Auto-generated by generate-assets.js
// ${new Date().toISOString()}
export const IMAGE_DATA = ${JSON.stringify(imageData, null, 2)};`;
  
  fs.writeFileSync(outputFile, content);
  
  console.log(`\n✅ Файл создан: ${outputFile}`);
  console.log(`📊 Изображений: ${countImages(imageData)}`);
  console.log(`📦 Размер: ${(content.length / 1024).toFixed(1)} KB`);
  
  // Проверяем наличие ключевых изображений
  checkRequiredImages(imageData);
}

function countImages(obj) {
  let count = 0;
  
  function countRecursive(data) {
    for (const key in data) {
      if (typeof data[key] === 'string' && data[key].startsWith('data:image')) {
        count++;
      } else if (typeof data[key] === 'object') {
        countRecursive(data[key]);
      }
    }
  }
  
  countRecursive(obj);
  return count;
}

function checkRequiredImages(imageData) {
  console.log('\n🔍 Проверка ключевых изображений:');
  
  const required = ['background', 'car', 'hatch', 'chicken'];
  const found = [];
  const missing = [];
  
  function searchRecursive(data, path = '') {
    for (const key in data) {
      const fullPath = path ? `${path}.${key}` : key;
      
      if (typeof data[key] === 'string' && data[key].startsWith('data:image')) {
        // Проверяем наличие ключевых слов
        for (const req of required) {
          if (key.toLowerCase().includes(req) || fullPath.toLowerCase().includes(req)) {
            if (!found.includes(req)) found.push(req);
          }
        }
      } else if (typeof data[key] === 'object') {
        searchRecursive(data[key], fullPath);
      }
    }
  }
  
  searchRecursive(imageData);
  
  required.forEach(req => {
    if (found.includes(req)) {
      console.log(`  ✓ ${req}`);
    } else {
      missing.push(req);
      console.log(`  ✗ ${req} - не найден`);
    }
  });
  
  if (missing.length > 0) {
    console.log(`\n⚠  Внимание: Отсутствуют ${missing.length} ключевых изображений`);
  }
}

// Запускаем основную функцию
main();